version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21
build:
    commands:
      - npm install --loglevel=error
      - RUN REACT_APP_API_URL=http://3.239.180.74 SKIP_PREFLIGHT_CHECK=true npm run build --prefix client
      - echo Rodando testes unitarios...
      - npm test
